package patches;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses the compact "levels.dat" resource format:
 *   id|rows|cols|row,col,value,shapeCode,solRow,solCol,solW,solH;row,col,...
 * One line per level. Generated by generate_levels.py from the same
 * puzzle generator used for the web version, so the two versions ship
 * identical puzzles.
 */
public final class LevelLoader {

    private LevelLoader() { }

    public static List<Level> loadAll() {
        List<Level> levels = new ArrayList<>();
        try (InputStream in = LevelLoader.class.getResourceAsStream("/levels.dat")) {
            if (in == null) throw new IllegalStateException("levels.dat resource not found on classpath");
            BufferedReader reader = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty()) continue;
                levels.add(parseLine(line));
            }
        } catch (IOException e) {
            throw new RuntimeException("Failed to load levels.dat", e);
        }
        return levels;
    }

    private static Level parseLine(String line) {
        String[] top = line.split("\\|", 4);
        int id = Integer.parseInt(top[0]);
        int rows = Integer.parseInt(top[1]);
        int cols = Integer.parseInt(top[2]);
        List<Clue> clues = new ArrayList<>();
        if (top.length > 3 && !top[3].isEmpty()) {
            for (String part : top[3].split(";")) {
                String[] f = part.split(",");
                int row = Integer.parseInt(f[0]);
                int col = Integer.parseInt(f[1]);
                int value = Integer.parseInt(f[2]);
                Shape shape = Shape.fromCode(f[3]);
                int solRow = Integer.parseInt(f[4]);
                int solCol = Integer.parseInt(f[5]);
                int solW = Integer.parseInt(f[6]);
                int solH = Integer.parseInt(f[7]);
                clues.add(new Clue(row, col, value, shape, solRow, solCol, solW, solH));
            }
        }
        return new Level(id, rows, cols, clues);
    }
}
